/**
 * @fileoverview Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name
 * @author Yann Braga
 */

//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

import { AST_NODE_TYPES } from '@typescript-eslint/utils'
import dedent from 'ts-dedent'

import rule from '../../../lib/rules/no-redundant-story-name'
import ruleTester from '../../utils/rule-tester'

//------------------------------------------------------------------------------
// Tests
//------------------------------------------------------------------------------

ruleTester.run('no-redundant-story-name', rule, {
  valid: [
    "export const PrimaryButton = { name: 'The Primary Button' }",
    "export const PrimaryButton: Story = { name: 'The Primary Button' }",
    `
      const Default = {}
      export const PrimaryButton = { ...Default, name: 'The Primary Button' }
    `,
    `
      export const PrimaryButton = Template.bind({})
      PrimaryButton.storyName = 'The Primary Button'
    `,
    `
      export function PrimaryButton () {
        return <div>Hello</div>
      }
      PrimaryButton.storyName = 'The Primary Button'
    `,
    `
      export function H1 () {
        return <h1>Hello</h1>
      }
      H1.storyName = 'H1'
    `,
  ],

  invalid: [
    {
      code: "export const PrimaryButton = { name: 'Primary Button' }",
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: AST_NODE_TYPES.Property,
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: 'export const PrimaryButton = {  }',
            },
          ],
        },
      ],
    },
    {
      code: "export const PrimaryButton: Story = { name: 'Primary Button' }",
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: AST_NODE_TYPES.Property,
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: 'export const PrimaryButton: Story = {  }',
            },
          ],
        },
      ],
    },
    {
      code: dedent`
        export const PrimaryButton = Template.bind({})
        PrimaryButton.storyName = 'Primary Button'
      `,
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: AST_NODE_TYPES.AssignmentExpression,
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: dedent`
                export const PrimaryButton = Template.bind({})

              `,
            },
          ],
        },
      ],
    },
  ],
})
