/**
 * @fileoverview Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name
 * @author Yann Braga
 */

//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

import { AST_NODE_TYPES } from '@typescript-eslint/types'

import rule from '../../../lib/rules/no-redundant-story-name'
import ruleTester from '../../utils/rule-tester'

//------------------------------------------------------------------------------
// Tests
//------------------------------------------------------------------------------

ruleTester.run('no-redundant-story-name', rule, {
  valid: [
    "export const PrimaryButton = { name: 'The Primary Button' }",
    "export const PrimaryButton: Story = { name: 'The Primary Button' }",
    `
      const Default = {}
      export const PrimaryButton = { ...Default, name: 'The Primary Button' }
    `,
  ],

  invalid: [
    {
      code: "export const PrimaryButton = { name: 'Primary Button' }",
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: AST_NODE_TYPES.Property,
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: 'export const PrimaryButton = {  }',
            },
          ],
        },
      ],
    },
    {
      code: "export const PrimaryButton: Story = { name: 'Primary Button' }",
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: AST_NODE_TYPES.Property,
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: 'export const PrimaryButton: Story = {  }',
            },
          ],
        },
      ],
    },
  ],
})
