/**
 * @fileoverview Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name
 * @author Yann Braga
 */
'use strict'

//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

// @ts-expect-error ts-migrate(2451) FIXME: Cannot redeclare block-scoped variable 'rule'.
const rule = require('../../../lib/rules/no-redundant-story-name'),
  // @ts-expect-error ts-migrate(2451) FIXME: Cannot redeclare block-scoped variable 'ruleTester... Remove this comment to see the full error message
  ruleTester = require('../../utils/rule-tester')

//------------------------------------------------------------------------------
// Tests
//------------------------------------------------------------------------------

ruleTester.run('no-redundant-story-name', rule, {
  valid: [
    "export const PrimaryButton = { name: 'The Primary Button' }",
    "export const PrimaryButton = { ...Default, name: 'The Primary Button' }",
  ],

  invalid: [
    {
      code: "export const PrimaryButton = { name: 'Primary Button' }",
      errors: [
        {
          messageId: 'storyNameIsRedundant',
          type: 'Property',
          suggestions: [
            {
              messageId: 'removeRedundantName',
              output: 'export const PrimaryButton = {  }',
            },
          ],
        },
      ],
    },
  ],
})
